//import Head from "next/head"
import { Inter } from "next/font/google"
import { Grid } from "@mui/material"
import { useTheme } from "@mui/material"
// const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const theme = useTheme()
  return (
    <Grid container className="home" width="1370px" justifyContent="center" mx="auto">
      <Grid item xs={12} px="2rem">
        <Grid container>
          <Grid item xs={6}>
            asdads
          </Grid>
          <Grid item xs={6}>
            asdasddasdasd
          </Grid>
        </Grid>
      </Grid>
    </Grid>
  )
}

{
  /* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */
}
